
/**
 * the idea is to store this to be able to restore the *last* theme generated by
 * the agent.
 */
export interface UIThemeInfo {
    /**
     * overrides from the default css variables.
     */
    cssVariableOverrides: { [key: string]: string; }
}
